### ISSUE TITLE
机器需要这么长时间才能拿到？

### ISSUE THREAD

**Issue by hx2nn** [Errrneist/Hackintosh-Legion-Y9000X#2]
我已经在我的机器上安装并运行了黑苹果。
现在来看问题集中：
1、声音无外放
2、电池百分比不更新（一直65%）
3、雷电转hdmi无反应（连usb移动硬盘好用，没有网口测试）
以上是目前的问题，希望能解决

**Comment by Errrneist** [comment]
人在美国 十二月中才放假回国拿机子 回国续一张签证再慢慢搞这个 
电池ACPIBattery加DSDT Patch解决 不知道该打哪个patch
声音可以试试VoodooHDA
雷电转HDMI我也不知道…

**Comment by hx2nn** [comment]
VoodooHDA黑果小兵帮我试了，不行。希望早点拿到机器能分享到你成果，本人小白一个只能等着。

**Comment by Errrneist** [comment]
> VoodooHDA黑果小兵帮我试了，不行。希望早点拿到机器能分享到你成果，本人小白一个只能等着。

我也不太会弄…还是开源社区强

**Comment by Errrneist** [comment]
> VoodooHDA黑果小兵帮我试了，不行。希望早点拿到机器能分享到你成果，本人小白一个只能等着。

有可能是BIOS不行，听说Linux也不好使，那就是Unix系统兼容不佳，我也没辙等后续更新吧。
